// Operadores aritmeticos
let salario=100;
console.log(salario+salario)
console.log(salario-salario)
console.log(salario*salario)
console.log(salario/salario)
console.log(salario**salario)
let idade = 18;
console.log(++idade)
console.log(++idade)
 // Operadores de atribuicao

 let = valortecladogamer=100;

 //valortecladogamer=valortecladogamer+valortecladogamer;
 valortecladogamer+=valortecladogamer;
 //valortecladogamer = valortecladogamer - valortecladogamer;
 valortecladogamer -= valortecladogamer;

 console.log(valortecladogamer);

 // Operadores de igualdade 
 // Igualdade restrita
 console.log( 1 === 1);
 console.log('2' === 2);

 //Igualdade solta
 console.log( 1 == 1);
 console.log('2' == 2)